on: workflow_dispatch

name: Generate-README.md-snake
  # You may pin to the exact commit or the version.
  uses: InvalidLenni/README.md@Template
  with:
    # <USERNAME>
   github_user_name: Queizen30
    # <PATH OF THE GENERATED SVG FILE>
   svg_out_path: /snake/snake.svh
          
