on:
  # manual run
  workflow_dispatch:
  # automatic daily run at 00:00 UTC
  schedule:
    - cron: '0 0 * * *'

# Allow the workflow to write repository contents when committing files
permissions:
  contents: write

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Generate GitHub snake images
        uses: Platane/snk@v3
        with:
          # github user name to read the contribution graph from (required)
          github_user_name: ${{ github.repository_owner }}

          # list of files to generate (one per line). Query-string style options supported.
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9&color_background=#aaaaaa

      - name: Commit generated files (if changed)
        uses: EndBug/add-and-commit@v9
        with:
          message: "baked you a cake and updated snake gifs"
          add: "dist/**"
          author_name: "github-actions"
          author_email: "41898282+github-actions[bot]@users.noreply.github.com"
          signoff: false
